# Generated by Django 4.1.5 on 2023-01-30 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('made_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_done', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('HI', 'HIGH'), ('MID', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='userToDo',
        ),
    ]
